jdbc:
  driverClassName: org.h2.Driver
  url: jdbc:h2:~/data/oauth2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  user: sa
  pass: sa

spring:
  h2.console.enabled: true
  profiles:
    active: jwtTokenStore
  
logging:
  level:
    org.springframework:
      security: DEBUG
 
application:
  security:
    keystore:
      alias: mytest
      path: mystore.jks
      pass: mypass
    token:
      access.validity.seconds: 3600
      refresh.validity.seconds: 36000
   
 
